services:
  - type: web
    name: schedulify-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SYNC_ALTER
        value: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_USER
        value: noreply@schedulify.com
